language: ruby
cache: bundler
rvm:
  - 2.6

install:
  - bundle install

# https://docs.travis-ci.com/user/build-stages
jobs:
  include:
    - stage: build
      script:
        - if [ ${TRAVIS_BRANCH} == production]; then export JEKYLL_ENV=production; fi
        - bundle exec jekyll build -d public
    - stage: test
      script:
        - bundle exec rake tests:schemas
    - stage: test
      script:
        - bundle exec rake tests:liens_public

deploy:
  local_dir: public
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: production
