$schema: http://json-schema.org/draft-07/schema#
title: QuestionReponse
description: Une question et sa réponse
type: object
required:
  - question
  - content
  - cible
  - categories
properties:
  question:
    type: string
    description: Question en texte brut
  content:
    type: string
    description: Réponse rédigée en markdown
  cible:
    type: string
    description: Public ciblé par la question
    enum:
      - general
      - individus
      - pme
  categories:
    type: array
    description: Liste de catégories reliées à la question
    uniqueItems: true
    items:
      type: string
      enum:
        - fraude
        - vie-privee
        - hammeconnage
        - attaque
        - appareils
