$schema: http://json-schema.org/draft-07/schema#
title: Pratique
description: Pratique cybersécuritaire à adopter
type: object
required:
  - title
  - description
  - content
  - niveau
  - tags
properties:
  title:
    type: string
    description: Nom de la pratique
  description:
    type: string
    description: Résumé de la pratique, rédigée en Markdown
  content:
    type: string
    description: Description détaillée de la pratique, rédigée en Markdown
  niveau:
    type: string
    description: Niveau de protection associé à la pratique
    enum:
      - basique
      - superieur
      - premium
  sources:
    type: object
    description: Nom de la source
    additionalProperties:
      type: string
      format: uri
      description: Liens vers les sources justifiant cette pratiques
  risques:
    type: array
    description: Risques prévenus par cette pratique
    uniqueItems: true
    items:
      type: string
      description: Nom du fichier du risque (sans l'extension)
  tags:
    type: array
    description: Liste de catégories reliées à l'article
    items:
      type: string
